// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9fuJwwuDtSULt_rdFEXYxIV3dmsyzOAg',
    appId: '1:833318025308:web:5529130f3950f2ee168e99',
    messagingSenderId: '833318025308',
    projectId: 'smart-electric-app',
    authDomain: 'smart-electric-app.firebaseapp.com',
    storageBucket: 'smart-electric-app.appspot.com',
    measurementId: 'G-82MFLFHEVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtKNjTT_fr-igNYunnf9Yjw_Il68PjfpM',
    appId: '1:833318025308:android:9a920aa70984f5f9168e99',
    messagingSenderId: '833318025308',
    projectId: 'smart-electric-app',
    storageBucket: 'smart-electric-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASCdXRVB61ugatqvNVGSfGt3N9L8scWlg',
    appId: '1:833318025308:ios:ac59ac033a51b707168e99',
    messagingSenderId: '833318025308',
    projectId: 'smart-electric-app',
    storageBucket: 'smart-electric-app.appspot.com',
    iosClientId: '833318025308-13qf1a12hvja99es050lqh12g2qgqju6.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartElectricApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASCdXRVB61ugatqvNVGSfGt3N9L8scWlg',
    appId: '1:833318025308:ios:ac59ac033a51b707168e99',
    messagingSenderId: '833318025308',
    projectId: 'smart-electric-app',
    storageBucket: 'smart-electric-app.appspot.com',
    iosClientId: '833318025308-13qf1a12hvja99es050lqh12g2qgqju6.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartElectricApplication',
  );
}
